version: '3.7'

services:
  sdocsweb:
    image: sdocs_admin_web
    restart: always
    build:
      context: ./
    working_dir: /usr/src/app
    container_name: sdocs_admin_web
    stdin_open: true
    tty: true
    volumes:
    - ./:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "8081:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
